spring.application.name=rest
spring.datasource.url=jdbc:mysql://Localhost:3307/rest_eventos?userSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Creamos las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

#Mustra las consultas SQL en la consola
spring.jpa.show-sql=true

#Formatea las consultas SQL en cosola par que sea legible
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de MailTrap servidor SMTP
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=e4df62e29fe668
#spring.mail.password=3287445935d07d
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# Configuración para GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=420082482@pcpuma.acatlan.unam.mx
spring.mail.password=nagjwdldoacltlxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true