spring.application.name=email_html_endpoint

# Comfiguracion de MailTrap servidor SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=31f9a5ff0b3a49
spring.mail.password=a7277f646a2d1d

# Propiedades para Jakarta Mail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true